### PR TITLE
Testing Pull request

### PR DESCRIPTION
**Pull request by PhillipDenmark**
@ Bunnymand 

What do you think mr corporate?

### CODE REVIEW

**Comment by PhillipDenmark** [comment]
;-)

**Comment by Bunnymand** [comment]
mr corporate no 2 I find it a bit difficult to navigate here. Perhaps you could profile your fun fun fun part a bit more

**Comment by PhillipDenmark** [comment]
@Bunnymand I have tried to add more fun with using bold typing. Do you like it?

**Comment by Bunnymand** [comment]
It is 4x as fun now. But we will be running out of eggs

**Pull request merged**
